version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    env_file: ./.env
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    networks:
      - backend
    platform: linux/x86_64

  web:
    image: $DOCKER_HUB_USER/running-map
    container_name: web
    env_file: ./.env
    restart: always
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - db
      - redis
    networks:
      - backend

  redis:
    image: redis:7.0
    container_name: redis
    env_file: ./.env
    restart: always
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend

networks:
  backend:
