name: build and test

on:
  pull_request_target:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/running-map:latest

  test:
    needs: build
    permissions:
            checks: write
            pull-requests: write
            contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : create coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm test
